declare const classNames: {
  readonly alata: "alata";
  readonly kronaone: "kronaone";
  readonly alegreyasans: "alegreyasans";
  readonly mulish: "mulish";
  readonly mainblue: "mainblue";
  readonly mainborder: "mainborder";
  readonly mainfont: "mainfont";
  readonly mainfontselected: "mainfontselected";
  readonly sectionContainer: "sectionContainer";
  readonly sectionWrapper: "sectionWrapper";
  readonly sectionTitle: "sectionTitle";
  readonly sectionDescription: "sectionDescription";
  readonly sectionButtons: "sectionButtons";
  readonly sectionButton: "sectionButton";
  readonly sectionSponsorButton: "sectionSponsorButton";
  readonly sectionProjectButton: "sectionProjectButton";
  readonly sectionNumberContainer: "sectionNumberContainer";
  readonly sectionArrow: "sectionArrow";
};
export = classNames;
