declare const classNames: {
  readonly alata: "alata";
  readonly kronaOne: "kronaOne";
  readonly alegreyaSans: "alegreyaSans";
  readonly mulish: "mulish";
  readonly mainBlue: "mainBlue";
  readonly mainBorder: "mainBorder";
  readonly mainFont: "mainFont";
  readonly mainFontSelected: "mainFontSelected";
  readonly sectionContainer: "sectionContainer";
  readonly videoPlaceholder: "videoPlaceholder";
  readonly sectionVideo: "sectionVideo";
  readonly sectionWrapper: "sectionWrapper";
  readonly sectionTitle: "sectionTitle";
  readonly sectionDescription: "sectionDescription";
  readonly sectionButtons: "sectionButtons";
  readonly sectionButton: "sectionButton";
  readonly sectionSponsorButton: "sectionSponsorButton";
  readonly sectionProjectButton: "sectionProjectButton";
  readonly sectionNumberContainer: "sectionNumberContainer";
  readonly sectionArrow: "sectionArrow";
};
export = classNames;
