declare const classNames: {
  readonly bevietnampro: "bevietnampro";
  readonly alata: "alata";
  readonly kronaone: "kronaone";
  readonly alegreyasans: "alegreyasans";
  readonly sectionContainer: "sectionContainer";
  readonly background: "background";
  readonly overlay: "overlay";
  readonly sectionWrapper: "sectionWrapper";
  readonly sectionTitle: "sectionTitle";
  readonly sectionDescription: "sectionDescription";
  readonly sectionButtons: "sectionButtons";
  readonly sectionButton: "sectionButton";
  readonly sectionSponsorButton: "sectionSponsorButton";
  readonly sectionProjectButton: "sectionProjectButton";
  readonly sectionNumberContainer: "sectionNumberContainer";
  readonly sectionNumberTitle: "sectionNumberTitle";
  readonly sectionMemberNumber: "sectionMemberNumber";
  readonly sectionYearNumber: "sectionYearNumber";
  readonly sectionStartNumber: "sectionStartNumber";
  readonly sectionNumber: "sectionNumber";
  readonly sectionArrow: "sectionArrow";
};
export = classNames;
