declare const classNames: {
  readonly alata: "alata";
  readonly kronaone: "kronaone";
  readonly alegreyasans: "alegreyasans";
  readonly mulish: "mulish";
  readonly mainblue: "mainblue";
  readonly mainborder: "mainborder";
  readonly mainfont: "mainfont";
  readonly mainfontselected: "mainfontselected";
  readonly container: "container";
  readonly background: "background";
  readonly firstIconCircle: "firstIconCircle";
  readonly secondIconCircle: "secondIconCircle";
  readonly wrapper: "wrapper";
  readonly paragraph: "paragraph";
  readonly firstWrapper: "firstWrapper";
  readonly secondWrapper: "secondWrapper";
  readonly numbersContainer: "numbersContainer";
  readonly paragraphImage: "paragraphImage";
};
export = classNames;
