declare const classNames: {
  readonly alata: "alata";
  readonly kronaOne: "kronaOne";
  readonly alegreyaSans: "alegreyaSans";
  readonly mulish: "mulish";
  readonly mainBlue: "mainBlue";
  readonly mainBorder: "mainBorder";
  readonly mainFont: "mainFont";
  readonly mainFontSelected: "mainFontSelected";
  readonly footerContainer: "footerContainer";
  readonly footerWrapper: "footerWrapper";
  readonly footerNavWrapper: "footerNavWrapper";
  readonly footerNav: "footerNav";
  readonly footerContent: "footerContent";
  readonly footerDivider: "footerDivider";
  readonly footerLogo: "footerLogo";
  readonly footerContentText: "footerContentText";
  readonly footerMailText: "footerMailText";
  readonly footerSocialWrapper: "footerSocialWrapper";
};
export = classNames;
