declare const classNames: {
  readonly alata: "alata";
  readonly kronaone: "kronaone";
  readonly alegreyasans: "alegreyasans";
  readonly mulish: "mulish";
  readonly mainblue: "mainblue";
  readonly mainborder: "mainborder";
  readonly mainfont: "mainfont";
  readonly mainfontselected: "mainfontselected";
  readonly footerContainer: "footerContainer";
  readonly footerWrapper: "footerWrapper";
  readonly footerNavWrapper: "footerNavWrapper";
  readonly footerNav: "footerNav";
  readonly footerContent: "footerContent";
  readonly footerDivider: "footerDivider";
  readonly footerLogo: "footerLogo";
  readonly footerContentText: "footerContentText";
  readonly footerMailText: "footerMailText";
  readonly footerSocialWrapper: "footerSocialWrapper";
};
export = classNames;
