name: Deploy

on:
  push:
    branches: 
    - test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.13.0

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run production

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        id: download
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
            server: pwrinspace.pwr.edu.pl
            username: ${{ secrets.SSH_LOGIN }}
            password: ${{ secrets.SSH_PASSWORD }}
            local-dir: ${{steps.download.outputs.download-path}}
            server-dir: test_deploy/

